# Many of the defaults are fine for our use.
# http://docs.pullapprove.com/yaml/
approve_by_comment: true
reset_on_reopened: true
reviewers:
    required: 1
    members:
      - blackbaud-bobbyearl
      - blackbaud-johnly
      - blackbaud-patrickofriel
      - blackbaud-paulcrowder
      - blackbaud-toddroberts
